name: GitHub-Activity-Readme
  # You may pin to the exact commit or the version.
on:
  schedule:
    #run every hour 
    - cron: "0 * * * *"

  workflow_dispatch:

jobs:
    build:
        name: Update README with the recent activity
        runs-on: ubuntu-latest

        permissions:
            contents: write
        
        steps:
            - name: Update the README with the recent activity
              uses: jamesgeorge007/github-activity-readme@v0.4.4
              
          